// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPluginLogs(arg1) {
  return window['go']['main']['App']['ClearPluginLogs'](arg1);
}

export function DisableMouseEvents() {
  return window['go']['main']['App']['DisableMouseEvents']();
}

export function EnableMouseEvents() {
  return window['go']['main']['App']['EnableMouseEvents']();
}

export function GetGhostPosX() {
  return window['go']['main']['App']['GetGhostPosX']();
}

export function GetGhostPosY() {
  return window['go']['main']['App']['GetGhostPosY']();
}

export function GetIconData(arg1) {
  return window['go']['main']['App']['GetIconData'](arg1);
}

export function GetIconURL(arg1) {
  return window['go']['main']['App']['GetIconURL'](arg1);
}

export function GetLastShortcutKeyID() {
  return window['go']['main']['App']['GetLastShortcutKeyID']();
}

export function GetMousePosX() {
  return window['go']['main']['App']['GetMousePosX']();
}

export function GetMousePosY() {
  return window['go']['main']['App']['GetMousePosY']();
}

export function GetMousePosition(arg1, arg2) {
  return window['go']['main']['App']['GetMousePosition'](arg1, arg2);
}

export function GetPluginDirectories() {
  return window['go']['main']['App']['GetPluginDirectories']();
}

export function GetPressedKeys() {
  return window['go']['main']['App']['GetPressedKeys']();
}

export function GetShiftDoublePressed() {
  return window['go']['main']['App']['GetShiftDoublePressed']();
}

export function ListPluginEntries(arg1) {
  return window['go']['main']['App']['ListPluginEntries'](arg1);
}

export function OpenMemo() {
  return window['go']['main']['App']['OpenMemo']();
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function ReadPluginLogs(arg1, arg2) {
  return window['go']['main']['App']['ReadPluginLogs'](arg1, arg2);
}

export function ReadPluginManifest(arg1) {
  return window['go']['main']['App']['ReadPluginManifest'](arg1);
}

export function ReadPluginModule(arg1, arg2) {
  return window['go']['main']['App']['ReadPluginModule'](arg1, arg2);
}

export function ResetShiftDoublePressed() {
  return window['go']['main']['App']['ResetShiftDoublePressed']();
}

export function ReturnFocusToPreviousWindow() {
  return window['go']['main']['App']['ReturnFocusToPreviousWindow']();
}

export function SetGhostPos(arg1, arg2) {
  return window['go']['main']['App']['SetGhostPos'](arg1, arg2);
}

export function SimulateKeyPress(arg1) {
  return window['go']['main']['App']['SimulateKeyPress'](arg1);
}

export function StartKeyMonitoring() {
  return window['go']['main']['App']['StartKeyMonitoring']();
}

export function StopKeyMonitoring() {
  return window['go']['main']['App']['StopKeyMonitoring']();
}

export function SwitchGhost(arg1) {
  return window['go']['main']['App']['SwitchGhost'](arg1);
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}

export function ValidatePluginDirectory(arg1) {
  return window['go']['main']['App']['ValidatePluginDirectory'](arg1);
}

export function ValidatePlugins() {
  return window['go']['main']['App']['ValidatePlugins']();
}

export function WriteClipboard(arg1) {
  return window['go']['main']['App']['WriteClipboard'](arg1);
}

export function WritePluginLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['WritePluginLog'](arg1, arg2, arg3);
}
