// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearPluginLogs(arg1:string):Promise<void>;

export function DisableMouseEvents():Promise<void>;

export function EnableMouseEvents():Promise<void>;

export function GetGhostPosX():Promise<number>;

export function GetGhostPosY():Promise<number>;

export function GetIconData(arg1:string):Promise<string>;

export function GetIconURL(arg1:string):Promise<string>;

export function GetLastShortcutKeyID():Promise<number>;

export function GetMousePosX():Promise<number>;

export function GetMousePosY():Promise<number>;

export function GetMousePosition(arg1:number,arg2:number):Promise<main.MousePosition>;

export function GetPluginDirectories():Promise<Array<string>>;

export function GetPressedKeys():Promise<string>;

export function GetShiftDoublePressed():Promise<boolean>;

export function ListPluginEntries(arg1:string):Promise<Array<main.DirectoryEntry>>;

export function OpenMemo():Promise<void>;

export function ReadClipboard():Promise<string>;

export function ReadPluginLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function ReadPluginManifest(arg1:string):Promise<main.GhostManifest>;

export function ReadPluginModule(arg1:string,arg2:string):Promise<string>;

export function ResetShiftDoublePressed():Promise<void>;

export function ReturnFocusToPreviousWindow():Promise<void>;

export function SetGhostPos(arg1:number,arg2:number):Promise<void>;

export function SimulateKeyPress(arg1:string):Promise<void>;

export function StartKeyMonitoring():Promise<void>;

export function StopKeyMonitoring():Promise<void>;

export function SwitchGhost(arg1:string):Promise<void>;

export function TakeScreenshot():Promise<void>;

export function ValidatePluginDirectory(arg1:string):Promise<Array<main.PluginValidationResult>>;

export function ValidatePlugins():Promise<Array<main.PluginValidationResult>>;

export function WriteClipboard(arg1:string):Promise<void>;

export function WritePluginLog(arg1:string,arg2:main.LogLevel,arg3:string):Promise<void>;
